project/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url('^hello/', views.hello)
]

project/kaiapp/urls.py
from django.conf.urls import url

from kaiapp import views

urlpatterns = [

    # 用户注册
    url(r'^register/', views.register, name='register'),
    # 用户登录
    url(r'^login/', views.login, name='login'),
    # 用户退出
    url(r'^logout/', views.logout, name='logout'),
    # 首页
    url(r'^index/', views.index, name='index'),

]

project/project/urls.py
from django.conf.urls import url, include
from django.views.static import serve

from project import settings

urlpatterns = [
    url(r'^app/', include('app.urls')),
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),  # 配置这个用来DEBUG等于False的时候可以加载静态文件
    url(r'kaiapp/', include('kaiapp.urls', namespace='kaiapp')),
    url(r'^detail/', include('detail.urls')),
    url(r'^cwd/', include('cwdapp.urls')),
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),  # 配置这个用来DEBUG等于False的时候可以加载静态文件
    # url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # 配置这个用来DEBUG等于False的时候去加载静态图片
    # url(r'^$', views.home),  # 通过空匹配返回首页
    url(r'^xym/', include(('xym.urls', 'xym'), namespace='xym')),
]

from django.contrib.staticfiles.urls import static
from project import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/xym/urls.py
from django.conf.urls import url

from xym import views


urlpatterns = [
    # url('^hello/', views.hello)
    #首页
    # url(r'^index/',views.my_home,name='my_index'),
    # #登录
    url(r'^login/',views.login,name='login'),
    # #注册
    # url(r'^register/',views.my_register,name='my_register'),
    #上传新房源
    url(r'^addnewhouse/',views.my_new_house,name='my_new_house'),
    #房源添加后展示
    # url(r'^shownewhouse/',views.show_newhouse,name='show_new_house'),
    #成功添加房源后跳转页面
    url(r'^success/', views.show_success, name='show_success'),
    # url(r'^removenewhouse/',views.remove_newhouse,name='remove_newhouse')


]

project/templates/cwd/adv.html
{% extends 'basr_my_min.html' %}
{% load static %}
{% block CSS %}
    <script type="text/javascript">
        $(function () {
            $(".leftnav h2").click(function () {
                $(this).next().slideToggle(200);
                $(this).toggleClass("on");
            })
            $(".leftnav ul li a").click(function () {
                $("#a_leader_txt").text($(this).text());
                $(".leftnav ul li a").removeClass("on");
                $(this).addClass("on");
            })
        });
    </script>
{% endblock %}
{% block div %}
    <div class="zxcf_nav_r fr">
    {% if user.avatar %}
        <a href="/cwd/myhouse/"><img src="{{ user.avatar }}" id="my_img" alt=""></a>
        <span>我的账户</span>
    {% else %}
        <a href="/cwd/myhouse/"><img src="{% static 'images/zxcf_perinfo.png' %}" alt=""></a>
        <span>我的账户</span>
    {% endif %}
{% endblock %}
{% block content %}


    <div class="admin">
        <div class="panel admin-panel">
            <div class="panel-head"><strong class="icon-reorder"> 内容列表</strong></div>
            <div class="padding border-bottom">
            </div>
            <table class="table table-hover text-center">

                <tr>
                    <th width="10%">ID</th>
                    <th width="20%">图片</th>
                    <th width="15%">名称</th>
                    <th width="20%">地区</th>
                    <th width="20%">房屋状态</th>
                    <th width="15%">操作</th>
                </tr>
                {% if user %}
                    {% for h in house %}
                        <tr id="awe{{ h.house_id }}">
                            <td>{{ h.house_id }}</td>
                            <td><img src="{{ h.index_img_url }}" alt="" width="120" height="50"/></td>
                            <td>{{ h.title }}</td>
                            <td>{{ h.address }}</td>
                            <td>{{ h.house_status }}</td>
                            <td>
                                <div class="button-group">
                                    <a class="button border-red" href="javascript:void(0)"
                                       onclick="return del({{ h.house_id }})"><span
                                            class="icon-trash-o"></span> 删除</a>

                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </table>
        </div>
        <script type="text/javascript">
            function del(id) {
                var r = confirm("您确定要删除吗?")
                if (r){
                    $.ajax({
                        type: 'GET',
                        url: '/cwd/del/',
                        contentType: 'application/json; charset=utf-8',
                        dataTYpe: 'json',
                        data:{'adv':id},
                        success: function (data) {
                            if(data.code=='200')
                            {alert(data.msg);
                            {#window.location.reload()表示刷新页面#}
                            $('#awe'+id).remove()}{#表示移除元素#}
                        },
                        error: function (data) {
                            alert('删除失败');
                            window.location.reload()
                        }
                    })}}
                    {#$.post('/cwd/like/', {h: id, csrfmiddlewaretoken: '{{ csrf_token }}'});#}
                    {#window.location.reload()#}
        </script>
    </div>
{% endblock %}

project/templates/cwd/find.html
{% extends 'base_mine.html' %}
{% load static %}
{% block title %}
    查询页
{% endblock %}

{% block content %}
    <div class="zscf_con_wper pb30">
        <div class="zscf_con px1000">
            <div class="zscf_block1 mt30 ">
                <h2 class="zscf_block1_tit clearfix"><span class="fl"><strong>查询房屋条件</strong></span>
                    <div class="clearfix clear" style="font-size: 20px">
                        {#                      {% for data in latest_data %}#}
                        <ul>区域:
                        <a href="/cwd/find/1/" style="margin: 0px 20px;font-size: 15px">不限</a>
                            {% for p in positions %}
                                <a href="/cwd/search/{{ p.area_id }}/0/0/1/" style="margin: 0px 20px;font-size: 15px">{{ p.name }}</a>
                            {% endfor %}
                        </ul>
                        <ul>价格:
                            <a href="/cwd/find/1/" style="margin: 0px 20px;font-size: 15px">不限</a>
                            <a href="/cwd/search/0/0-500/0/1/" style="margin: 0px 20px;font-size: 15px">500元以下</a>
                            <a href="/cwd/search/0/500-1000/0/1/" style="margin: 0px 20px;font-size: 15px">500-1000元</a>
                            <a href="/cwd/search/0/1000-2000/0/1/" style="margin: 0px 20px;font-size: 15px">1000-2000元</a>
                            <a href="/cwd/search/0/2000-3000/0/1/" style="margin: 0px 20px;font-size: 15px">2000-3000元</a>
                            <a href="/cwd/search/0/3000-1000000/0/1/" style="margin: 0px 20px;font-size: 15px">3000以上元</a>
                        </ul>
                        <ul>房型:
                        <a href="/cwd/find/1/" style="margin: 0px 20px;font-size: 15px">不限</a>
                            {% for n in new_type %}
                                <a href="/cwd/search/0/0/{{ n }}/1/" style="margin: 0px 10px;font-size: 15px">{{ n }}</a>
                            {% endfor %}
                        </ul>
                    </div>
            </div>
        </div>
    </div>



    <!-- 这里结束 -->

    <div class="zscf_con_wper pb30">
        <div class="zscf_con px1000">
            <div class="zscf_block3 mt30 ">
                <h2 class="block3_tit clearfix"><span class="block3_curspan">最新发布房源</span><em><img
                </em></h2>
                <div class="block3_pro_box clear">
                    <div class="block3_prolist">
                        {% for i in houses %}

                            <div class="block3_proone clearfix clear">
                                <span class="fl proone_left">     <div class="tjxm_jindu ">

                                            </div></span>
                                <!--  -->
                                <div class="fl proone_center">
                                    <div class="clearfix">
                                        <span class="fl proone_center_span1">{{ i.title }}</span>
                                        <div class="block2_biao_r fr">

                                        </div>
                                    </div>

                                    <ul class="clearfix proone_center_ul clear pt10">
                                        <li>租金:<span>{{ i.price }}元</span></li>
                                        <li>房间平米:<span>{{ i.acreage }}m²</span></li>
                                        <li>区域：<span>{{ i.address }}</span></li>
                                    </ul>
                                </div>
                                <!--  -->
                                <a href="/detail/detail/{{ i.house_id }}/" class="block3_btn fl">查看详情</a>
                                <img src="{{ i.index_img_url }}"
                                     data-img="{{ i.index_img_url }} " alt="{{ i.title }}"
                                     style="width: 140px ;height: 100px; ">

                            </div>
                        {% endfor %}
                        <div class="ui_flt" style="height: 30px; line-height: 30px;">
                            共有
                            <span class="ui_txt_bold04">{{ all_record }}</span>
                            条记录，当前第
                            <span class="ui_txt_bold04">{{ the_page }}
						/
                                {{ total_page }}</span>
                            页
                        </div>
                        <div class="ui_frt">
                            <!--    如果是第一页，则只显示下一页、尾页 -->

                            <a href="/cwd/find/1/"><input type="button" value="首页" class="ui_input_btn01"></a>

                            {% if the_page > 1 %}
                                <a href="/cwd/find/{{ the_page|add:-1 }}/"><input id='foo1' type="button" value="上一页"
                                                                                  class="ui_input_btn01"/></a>
                            {% else %}
                                <a href="/cwd/find/{{ the_page }}/"><input id='foo1' type="button" value="上一页"
                                                                           class="ui_input_btn01"/></a>
                            {% endif %}

                            {% if the_page < total_page %}
                                <a href="/cwd/find/{{ the_page|add:1 }}/"><input type="button" value="下一页"
                                                                                 class="ui_input_btn01"></a>
                            {% else %}
                                <a href="/cwd/find/{{ the_page }}/"><input type="button" value="下一页"
                                                                           class="ui_input_btn01"></a>
                            {% endif %}


                            <a href="/cwd/find/{{ total_page }}/"><input type="button" value="尾页"
                                                                         class="ui_input_btn01"></a>


                            <!--     如果是最后一页，则只显示首页、上一页 -->
                            <form style="float: right">


                                转到第<input type="text" id="jumpNumTxt" class="ui_input_txt01">页
                                <input type="button" id="gotosearch" class="ui_input_btn01" value="跳转"
                                       onclick="search()">

                                <input type="text" style="display: none">
                                <input id="foo2" type="hidden" value="{{ total_page }}">
                            </form>


                        </div>
                    </div>
                    <!-- end 项目列表 -->
                    <div class="block3_prolist" style="display:none;">
                        2
                    </div>
                </div>
            </div>
            <!-- end block3 -->
            <div class="zscf_block4 mt30">
                <img src="{% static 'images/timg.jpg' %}">
            </div>
            <!-- end block4 -->
{% endblock %}

project/templates/cwd/index.html
{% extends 'base_mine.html' %}
{% load static %}
{% block title %}
首页
{% endblock %}


{% block content %}

        <!-- end  -->
        <div class="zscf_banner_wper">
            <div class="zscf_banner px1000">
                <div class="zscf_box">
                    <strong>中兴租房</strong>
                    <p>累计成交：<strong>56789次</strong></p>
                    <p>运营时间：<strong>123天</strong></p>
                    {#               如果用户未登录#}
               {% if request.session.account == null %}
                    <a href="{% url 'kaiapp:login' %}" class="btn btn1">立即登录</a><br>
                    <a href="{% url 'kaiapp:register' %}" class="btn btn2">立即注册</a>

{#               如果用户已登录，且存在nick_name#}
               {% elif request.session.account and one_data.nick_name %}
                   <a href="#" class="btn btn1">{{ one_data.nick_name }}</a><br>
                   <a href="{% url 'kaiapp:logout' %}" class="btn btn2">安全退出</a>

{#                如果用户已登录，且未修改nick_name#}
               {% else %}
                   <a href="#" class="btn btn1">{{ request.session.account }}</a><br>
                   <a href="{% url 'kaiapp:logout' %}" class="btn btn2">安全退出</a>

               {% endif %}
                </div>
            </div>
        </div>
        <!-- end banner -->
        <div class="zscf_con_wper pb30">
        <div class="zscf_con px1000">
        <div class="zscf_block3 mt30 ">
            <h2 class="block3_tit clearfix"><span class="block3_curspan">最新发布房源</span><em><img
                    src="images/shu.png"
                    alt=""></em></h2>
            <div class="block3_pro_box clear">
                <div class="block3_prolist">
                    {% for i in hous %}

                        <div class="block3_proone clearfix clear">
                                <span class="fl proone_left">     <div class="tjxm_jindu ">

                                            </div></span>
                            <!--  -->
                            <div class="fl proone_center">
                                <div class="clearfix">
                                    <span class="fl proone_center_span1">{{ i.title }}</span>
                                    <div class="block2_biao_r fr">

                                    </div>
                                </div>

                                <ul class="clearfix proone_center_ul clear pt10">
                                    <li>租金:<span>{{ i.price }}元</span></li>
                                    <li>房间平米:<span>{{ i.acreage }}m²</span></li>
                                    <li>区域：<span>{{ i.address }}</span></li>
                                </ul>
                            </div>
                            <!--  -->
                            <a href="/detail/detail/{{ i.house_id }}/" class="block3_btn fl">查看详情</a>
                            <img src="{{ i.index_img_url }}"
                                 data-img="{{ i.index_img_url }} " alt="{{ i.title }}"
                                 style="width: 140px ;height: 100px; ">

                        </div>
                    {% endfor %}
                </div>
                <!-- end 项目列表 -->
                <div class="block3_prolist" style="display:none;">
                    2
                </div>
            </div>
        </div>
        <!-- end block3 -->
        <div class="zscf_block4 mt30">
            <img src="{% static 'images/timg.jpg' %}">
        </div>
        <!-- end block4 -->

    {% endblock %}

project/templates/cwd/login.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="renderer" content="webkit">
    <title>登录</title>  
    <link rel="stylesheet" href="css/pintuer.css">
    <link rel="stylesheet" href="css/admin.css">
    <script src="js/jquery.js"></script>
    <script src="js/pintuer.js"></script>  
</head>
<body>
<div class="bg"></div>
<div class="container">
    <div class="line bouncein">
        <div class="xs6 xm4 xs3-move xm4-move">
            <div style="height:150px;"></div>
            <div class="media media-y margin-big-bottom">           
            </div>         
            <form action="index.html" method="post">
                {% csrf_token %}
            <div class="panel loginbox">
                <div class="text-center margin-big padding-big-top"><h1>后台管理中心</h1></div>
                <div class="panel-body" style="padding:30px; padding-bottom:10px; padding-top:10px;">
                    <div class="form-group">
                        <div class="field field-icon-right">
                            <input type="text" class="input input-big" name="name" placeholder="登录账号" data-validate="required:请填写账号" />
                            <span class="icon icon-user margin-small"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="field field-icon-right">
                            <input type="password" class="input input-big" name="password" placeholder="登录密码" data-validate="required:请填写密码" />
                            <span class="icon icon-key margin-small"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="field">
                            <input type="text" class="input input-big" name="code" placeholder="填写右侧的验证码" data-validate="required:请填写右侧的验证码" />
                           <img src="images/passcode.jpg" alt="" width="100" height="32" class="passcode" style="height:43px;cursor:pointer;" onclick="this.src=this.src+'?'">  
                                                   
                        </div>
                    </div>
                </div>
                <div style="padding:30px;"><input type="submit" class="button button-block bg-main text-big input-big" value="登录"></div>
            </div>
            </form>          
        </div>
    </div>
</div>

</body>
</html>

project/templates/cwd/my_house.html
{% extends 'basr_my_min.html' %}
{% load static %}
{% block CSS %}
    <script type="text/javascript">
        $(function () {
            $(".leftnav h2").click(function () {
                $(this).next().slideToggle(200);
                $(this).toggleClass("on");
            })
            $(".leftnav ul li a").click(function () {
                $("#a_leader_txt").text($(this).text());
                $(".leftnav ul li a").removeClass("on");
                $(this).addClass("on");
            })
        });
    </script>
{% endblock %}
{% block div %}
    <div class="zxcf_nav_r fr">
    {% if user.avatar %}
        <a href="/cwd/myhouse/"><img src="{{ user.avatar }}" id="my_img" alt=""></a>
        <span>我的账户</span>
    {% else %}
        <a href="/cwd/myhouse/"><img src="{% static 'images/zxcf_perinfo.png' %}" alt=""></a>
        <span>我的账户</span>
    {% endif %}
{% endblock %}
{% block content %}


    <div class="admin">
        <div class="panel admin-panel">
            <div class="panel-head"><strong class="icon-reorder"> {{ user.account }}发布的房源</strong></div>
            <div class="padding border-bottom">
            </div>
            <table class="table table-hover text-center">
            <tr>
                            <th width="10%">ID</th>
                            <th width="20%">图片</th>
                            <th width="15%">名称</th>
                            <th width="15%">地区</th>
                            <th width="10%">价格</th>
                            <th width="20%">房屋状态</th>
                            <th width="15%">操作</th>
                        </tr>
                {% if user %}
                    {% for h in house %}


                        <tr id="awe{{ h.house_id }}">
                            <td>{{ h.house_id }}</td>
                            <td><img src="{{ h.index_img_url }}" alt="" width="120" height="50"/></td>
                            <td>{{ h.title }}</td>
                            <td>{{ h.address }}</td>
                            <td>{{ h.price }}</td>
                            <td>{{ h.house_status }}</td>
                            <td>
                                <div class="button-group">
                                    <a class="button border-red" href="javascript:void(0)"
                                       onclick="return del({{ h.house_id }})"><span
                                            class="icon-trash-o"></span> 删除</a>

                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </table>
        </div>

        <script type="text/javascript">
            function del(id) {
                var r = confirm("您确定要删除吗?")
                if (r){
                    $.ajax({
                        type: 'GET',
                        url: '/cwd/del/',
                        contentType: 'application/json; charset=utf-8',
                        dataTYpe: 'json',
                        data:{'myhouse':id},
                        success: function (data) {
                            if(data.code=='200')
                            {alert(data.msg);
                            {#window.location.reload()表示刷新页面#}
                            $('#awe'+id).remove()}{#表示移除元素#}
                        },
                        error: function (data) {
                            alert('删除失败');
                            window.location.reload()
                        }
                    })}}
        </script>
    </div>
{% endblock %}

project/templates/cwd/page.html
{% extends 'basr_my_min.html' %}
{% load static %}
{% block CSS %}
    <script type="text/javascript">
        $(function () {
            $(".leftnav h2").click(function () {
                $(this).next().slideToggle(200);
                $(this).toggleClass("on");
            })
            $(".leftnav ul li a").click(function () {
                $("#a_leader_txt").text($(this).text());
                $(".leftnav ul li a").removeClass("on");
                $(this).addClass("on");
            })
        });
    </script>
{% endblock %}
{% block div %}
    <div class="zxcf_nav_r fr">
    {% if user.avatar %}
        <a href="/cwd/myhouse/"><img src="{{ user.avatar }}" id="my_img" alt=""></a>
        <span>我的账户</span>
    {% else %}
        <a href="/cwd/myhouse/"><img src="{% static 'images/zxcf_perinfo.png' %}" alt=""></a>
        <span>我的账户</span>
    {% endif %}
{% endblock %}

{% block content %}


    <div class="admin">
        <div class="panel admin-panel">
            {% if user.nick_name %}
                <div class="panel-head"><strong><span class="icon-pencil-square-o"></span>欢迎你:{{ user.nick_name }}
                </strong><img src="{{ user.avatar }}" style="width: 100px;height: 100px">
                </div>
            {% else %}
                <div class="panel-head"><strong><span class="icon-pencil-square-o"></span>欢迎你:{{ user.account }}
                </strong>
                    <img src="{{ user.avatar }}" style="width: 100px;height: 100px"></div>
            {% endif %}
            <div class="body-content">
                <form method="post" class="form-x" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="label">
                            <label>设置昵称：</label>
                        </div>
                        <div class="field">
                            <input type="text" class="input" name="nick_name" value=""/>
                            <div class="tips"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label>设置头像：</label>
                        </div>
                        <div class="field">

                            <input name="avatar" type="file" class="button bg-blue margin-left" id="image1"
                                   value="+ 浏览上传"
                                   style="float:left;">
                            <div class="tipss">图片尺寸：500*200</div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label></label>
                        </div>
                        <div class="field">
                            <button class="button bg-main icon-check-square-o" type="submit"> 提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

project/templates/cwd/pass.html
{% extends 'basr_my_min.html' %}
{% load static %}
{% block CSS %}


<script type="text/javascript">
    $(function () {
        $(".leftnav h2").click(function () {
            $(this).next().slideToggle(200);
            $(this).toggleClass("on");
        })
        $(".leftnav ul li a").click(function () {
            $("#a_leader_txt").text($(this).text());
            $(".leftnav ul li a").removeClass("on");
            $(this).addClass("on");
        })
    });
</script>
{% endblock %}
{% block div %}
    <div class="zxcf_nav_r fr">
    {% if user.avatar %}
        <a href="/cwd/myhouse/"><img src="{{ user.avatar }}" id="my_img" alt=""></a>
        <span>我的账户</span>
    {% else %}
        <a href="/cwd/myhouse/"><img src="{% static 'images/zxcf_perinfo.png' %}" alt=""></a>
        <span>我的账户</span>
    {% endif %}
{% endblock %}
{% block content %}


<div class="admin">
    <div class="panel admin-panel">
        <div class="panel-head"><strong><span class="icon-key"></span> 修改会员密码</strong></div>
        <div class="body-content">

                <div class="form-group">
                    <div class="label">
                        <label for="sitename">会员帐号：</label>
                    </div>
                    <div class="field">
                        <label style="line-height:33px;">
                            {{ user.account }}
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="label">
                        <label for="sitename">会员手机号：</label>
                    </div>
                    <div class="field">
                        <label style="line-height:33px;">
                            {{ user.phone }}
                        </label>
                    </div>
                </div>
            <form method="post" class="form-x" action="">
                {% csrf_token %}
                <div class="form-group">
                    <div class="label">
                        <label for="sitename">原始密码：</label>
                    </div>
                    <div class="field">
                        <input type="password" class="input w50" id="mpass" name="mpass" size="50" placeholder="请输入原始密码"
                               data-validate="required:请输入原始密码"/>
                    </div>
                </div>
                <div class="form-group">
                    <div class="label">
                        <label for="sitename">新密码：</label>
                    </div>
                    <div class="field">
                        <input type="password" class="input w50" name="newpass" size="50" placeholder="请输入新密码"
                               data-validate="required:请输入新密码,length#>=5:新密码不能小于5位"/>
                    </div>
                </div>
                <div class="form-group">
                    <div class="label">
                        <label for="sitename">确认新密码：</label>
                    </div>
                    <div class="field">
                        <input type="password" class="input w50" name="renewpass" size="50" placeholder="请再次输入新密码"
                               data-validate="required:请再次输入新密码,repeat#newpass:两次输入的密码不一致"/>
                    </div>
                </div>

                <div class="form-group">
                    <div class="label">
                        <label></label>
                    </div>
                    <div class="field">
                        <button type="submit" class="button bg-main icon-check-square-o" > 提交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}