day11axf0/axf/urls.py
from django.conf.urls import url

from axf import views
urlpatterns = [
    # 首页
    url(r'^home/', views.home, name='home'),
    # 个人中心
    url(r'^mine/', views.mine, name='mine'),
    url(r'^userregister/', views.user_register, name='user_register'),
    url(r'^userlogout/', views.user_logout, name='user_logout'),
    url(r'^userlogin/', views.user_login, name="user_login"),

    # 闪购
    url(r'^market/$', views.user_market, name='market'),
    url(r'^market/(\d+)/(\d+)/(\d+)/', views.user_market_params, name='marketparams'),

    # 添加购物车
    url(r'^addgoods/', views.add_goods, name='addgoods'),
    url(r'^subgoods/', views.sub_goods, name='subgoods'),

    # 购物车
    url(r'^cart/', views.user_cart, name='cart'),
    # 修改购物车商品的选择
    url(r'^changeCartSelect/', views.user_change_select, name='change_select'),

    # 下单
    url(r'^generateOrder/', views.user_generate_order, name='user_generate_order'),

    # 付款
    url(r'^payOrder/(\d+)/', views.user_pay_order, name='user_pay_order'),
    # 确认付款
    url(r'^OrderPayed/(\d+)/', views.order_pay, name='order_pay'),

    # 代付款订单
    url(r'orderWaitPay', views.order_wait_pay, name='ordr_Wait_pay'),

    # 待收货
    url(r'^orderpayed/', views.order_wait_shouhuo, name='order_wait_shouhuo'),


]

day11axf0/day11axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from day11axf import settings

from django.views.static import serve

from axf import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('axf.urls', namespace='axf')),
    # url(r'^static/(?P<path>.*)$', serve, {"document_root": settings.STATIC_ROOT}),
    url(r'^$', views.home)
]

day11axf0/templates/mine/mine.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/mine/mine.css' %}">
{% endblock %}

{% block EXTJS %}
{{ block.super }}
    <script type="text/javascript" src="{% static 'app/mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="mine">

        <div class="fixed">
            <!--如果登录，展示头像-->
            {% if user.username %}
                <img src="{{ user.icon }}" alt="icon">
            {% else %}
            <!--或者-->
                <span class="glyphicon glyphicon-user"></span>
            <!--判断结束-->
            {% endif %}
            {% if user.username %}
            <!--如果登录，展示姓名-->
                <p>{{ user.username }}111</p>
            <!--或者展示登录的链接-->
            {% else %}
                <a href="{% url 'axf:user_login' %}">登录</a>
            <!--判断结束-->
            {% endif %}

            <p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>
            <!--如果没有登录,展示注册信息-->
            {% if not user.username %}
                <div id="regis">
                    <a href="{% url 'axf:user_register' %}">注册</a>
                </div>
            {% endif %}
            <!--判断结束-->

            <p><span class="glyphicon glyphicon-heart"></span><span>收藏</span></p>

        </div>

        <div class="mine">

            <p>我的订单<a href="#">更多&gt;</a></p>

            <div id="nav">

                <ul>
                    <a href="{% url 'axf:ordr_Wait_pay' %}" >
                        <li>
                            <dl>
                                <dt><span id="wait_pay_list" class="glyphicon glyphicon-usd"></span>
                                    <span class="badge">
                                        <!--代付款的数量-->
                                        {{ wait_pay }}
                                    </span></dt>
                                <dd>待付款</dd>
                            </dl>

                        </li>
                    </a>
                    <a href="{% url 'axf:order_wait_shouhuo' %}">
                        <li>
                            <dl>
                                <dt><span id="order_payed_list" class="glyphicon glyphicon-envelope"></span>
                                    <span class="badge">
                                        <!--待收货的数量-->
                                        {{ payed }}
                                    </span></dt>
                                <dd>待收货</dd>
                            </dl>

                        </li>
                    </a>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-pencil"></span></dt>
                            <dd>待评价</dd>
                        </dl>

                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-retweet"></span></dt>
                            <dd>退款/售后</dd>
                        </dl>

                    </li>

                </ul>

            </div>

            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                            <span>积分商城</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                            <span>优惠券</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-import"></span></dt>
                            <span>收货地址</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
                            <span>客户反馈</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-certificate"></span></dt>
                            <span>关于我们</span>
                        </dl>
                    </li>
                </ul>
            </menu>

            <!--如果登录了,则退出展示-->

                <p class="logout">
                    <a href="{% url 'axf:user_logout' %}">退出</a>
                </p>
            <!--判断结束-->
        </div>
    </div>


{% endblock %}